name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "31 1 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: python -m pip install httpx mwclient

      - run: python -m whats_new -u
        id: update
        env:
          HUIJIWIKI_PASSWORD: ${{ secrets.HUIJIWIKI_PASSWORD }}
          PYTHONOPTIMIZE: ${{ vars.PYTHONOPTIMIZE }}

      - if: ${{ steps.update.outputs.need_upload }}
        run: python -m whats_new -d
      
      - if: ${{ steps.update.outputs.need_upload }}
        uses: softprops/action-gh-release@v2
        with:
          body_path: whats_new.txt
          tag_name: ${{ steps.update.outputs.vers }}
          files: *.apk
