name: Update whats_new to wiki

on:
  workflow_dispatch:
  schedule:
    - cron: '59 1 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: python -m pip install httpx mwclient

      - run: python -m whats_new -u
        env: 
          HUIJIWIKI_PASSWORD: ${{ secrets.HUIJIWIKI_PASSWORD }}