name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "25 1 * * *"

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: "pip"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Update huijiwiki and release
        id: update
        env:
          HUIJIWIKI_PASSWORD: ${{ secrets.HUIJIWIKI_PASSWORD }}
          HUIJIWIKI_KEY: ${{ secrets.HUIJIWIKI_KEY }}
          PYTHONOPTIMIZE: ${{ vars.PYTHONOPTIMIZE }}
        run: |
          export git_tag=`git tag`
          python -m whats_new -u
          python -m whats_new -d

      - if: ${{ steps.update.outputs.need_upload }}
        uses: softprops/action-gh-release@v2
        with:
          body_path: whats_new.txt
          tag_name: ${{ steps.update.outputs.new_vers }}
          files: ./*.apk
